### ISSUE TITLE
How important is bundle.close()?

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#10]
Comments in `rollup/rollup.ts` say "Once you're finished with the `bundle` object, you should call `bundle.close()`". `cli/build.ts` does this, but `example/rollup.build.ts` and the API example in the Readme do not. Should they?

**Comment by cmorten** [comment]
As best practice they should yes, see https://rollupjs.org/guide/en/#rolluprollup

This is to ensure Rollup / plug-ins clean up properly. In simple examples which immediate end  post bundle it is not too much of an issue as the runtime will terminate and likely clean-up, but worth having in our examples so they can be used for “best practice” reference.
