### ISSUE TITLE
Bug: rollup/write.ts dir option needs to create subdirs

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#11]
# Issue

Setup:

- deno-rollup version: 2.38.0+0.7.0

When using `dir` output option, chunks in subdirs are failing if the subdir does not exist

## Details
Example options:
```
  input: {
    "chunk1": "./lib/chunk1.js",
    "subdir/chunk2": "./lib/subdir/chunk2.js"
  },
  output: {
    "dir": "output/"
```
Looks like `Deno.writeTextFile()` does not auto-create directories in path.

**Comment by cmorten** [comment]
Curious! So we handle the creation of the output `dir` with:

```ts
await Deno.mkdir(destination, { recursive: true });
```

REF: https://github.com/cmorten/deno-rollup/blob/main/src/rollup/write.ts#L34

But nothing special is being done for the inputs - what is the expected behaviour in this case, that there is a `output/subdir/chunk2.js`?

**Comment by cmorten** [comment]
Please see `2.38.0+0.7.1`

**Comment by probins** [comment]
yup, that seems to have fixed the problem, thanks.

I use this myself to maintain the same directory structure when splitting code, so the button links are the same for loading from source and from build.
