### ISSUE TITLE
svelte plugin

### ISSUE THREAD

**Issue by buttercubz** [cmorten/deno-rollup#19]
some plan add plugin to bundle svelte apps?

**Comment by cmorten** [comment]
Hey @buttercubz 👋 

Not on my personal list atm, but very open to contributions if this is something you need 😊

As a starter for 10, I’d see if any existing plugins from the Node ecosystem do the job for you, for instance https://esm.sh/rollup-plugin-svelte might cut it ( haven’t tested! ). If not, happy to house something in this repo or feel free to create your own plugin module for elswhere 🙃

**Comment by buttercubz** [comment]
> Hey @buttercubz 👋
> 
> Not on my personal list atm, but very open to contributions if this is something you need 😊
> 
> As a starter for 10, I’d see if any existing plugins from the Node ecosystem do the job for you, for instance https://esm.sh/rollup-plugin-svelte might cut it ( haven’t tested! ). If not, happy to house something in this repo or feel free to create your own plugin module for elswhere 🙃

thanks

**Comment by buttercubz** [comment]
I was able to make the plugin to minimize svelte, I am testing it in case it works fine, it could be added to plugin list, btw nice work deno-rollup work really fine

**Comment by cmorten** [comment]
Ah awesome work - happy to host a link to it, example or code in this repo no problem 🙂 let me know!

**Comment by cmorten** [comment]
Closed via https://github.com/cmorten/deno-rollup/pull/21
