### ISSUE TITLE
Watch not re-bundling on changes

### ISSUE THREAD

**Issue by denyncrawford** [cmorten/deno-rollup#32]
# Rollup is tot watching the changes at the included directories.

If the `watch.include` option is set, the watcher will not work or watch on the desired directory.

Setup:

- Deno version: 1.9.1 / 1.8.x
- v8 version: 9.1.269.5
- Typescript version: 4.2.2
- deno-rollup version: 2.42.3+0.17.1

## Details

I am trying to test my modules and importing them whether or not it makes no difference in behavior, it is not watchin changes in my src directory.

### rollup.watch.ts

```typescript
import live from 'https://deno.land/x/drollup_plugin_livereload/mod.ts'
import serve from 'https://deno.land/x/drollup_plugin_serve/mod.ts'
import { watch  } from "https://deno.land/x/drollup/mod.ts";

const options =  {
  input: 'src/entry.ts',
  output: {
    file: 'src/dest.js',
    format: 'es' as const,
  },
  plugins: [
    serve({ contentBase: 'src', port: Math.round(Math.random() * 10000) + 40000 }),
    live(['src'])
  ],
  watch: {
    include: ['src/**']
  },
}

const watcher = await watch(options);

watcher.on("event", (event) => {
  if (event.code === "BUNDLE_END") {
    event.result.close();
  }
});

```

### There's no error message:
![image](https://user-images.githubusercontent.com/28849055/115709257-62c4c400-a347-11eb-93a8-c81d3b10c276.png)

It doesn't work with the CLI either, and if I don't set any watch options it will bundle in loop forever.

[EDIT]: [This is the reproduction directory](https://github.com/cmorten/deno-rollup/tree/main/examples/livereload)

**Comment by denyncrawford** [comment]
Well I am testing with `watch.exclude` and it is not working either, can it be possible that there is a problem with the filter?

**Comment by lfmaciasr** [comment]
Had the same issue, I made it work on Windows with the following configuration:

    watch: {
      include: [
        '*\src\*'
      ]
    },

**Comment by cmorten** [comment]
Deprecating this repo in favour of using the official Rollup project + compat layer. Feel free to fork to resolve issues.
