### ISSUE TITLE
Uncaught errors

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#44]
I run deno-rollup on some software which doesn't change very often, and I've not bothered keeping up to date on new versions. I've just run this today, and I'm getting:
```
error: Uncaught (in promise) Error
    base = Object.assign(new Error(base.message), base);
                         ^
    at error (https://deno.land/x/drollup@2.38.4+0.10.0/src/error.ts:11:26)
    at rollup (https://deno.land/x/drollup@2.38.4+0.10.0/src/rollup/rollup.ts:66:14)
```
I tried using the latest release, and get the same thing:
```
error: Uncaught (in promise) Error
    base = Object.assign(new Error(base.message), base);
                         ^
    at error (https://deno.land/x/drollup@2.58.0+0.20.0/src/error.ts:15:26)
    at rollup (https://deno.land/x/drollup@2.58.0+0.20.0/src/rollup/rollup.ts:67:14)
```
I then tried reversing my change, so my software was in exactly the same state as when I last ran it (successfully), but get the same result.

So, rollup seems to be objecting to something it wasn't objecting to before, and then deno-rollup is not catching these errors, making it hard to work out exactly what's going on.

I've just upgraded Deno to 1.17.2, with the same result.

PS I see your Readme note on changing to Node compatibility layer. If you've not seen this, the basic functionality is now implemented, and discussion has moved on to https://github.com/denoland/deno/issues/12577 I see discussion of Parcel and Webpack, but not Rollup. If this can be implemented quickly, as you say, it might be better to concentrate on that rather than fix this issue. The changes I want to make to my software aren't particularly urgent (minor new features rather than bugs), so could wait for a while.

**Comment by milotheirself** [comment]
Are there any updates on this? 

I'm getting a similar error with no description, from code that worked with a previous version of Deno.

```plain
Error
    at error (https://deno.land/x/drollup@2.58.0+0.20.0/src/error.ts:15:26)
    at rollup (https://deno.land/x/drollup@2.58.0+0.20.0/src/rollup/rollup.ts:67:14)
```

**Comment by cmorten** [comment]
Deprecating this repo in favour of using the official Rollup project + compat layer. Feel free to fork to resolve issues.
