### ISSUE TITLE
Suggestion: run example remotely

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#5]
# Issue
Example(s) can be run remotely, in the Deno style.

## Details
I created a local config file:
```js
import { rollup } from "https://deno.land/x/drollup@2.37.1+0.5.1/mod.ts";
const options = {
  input: "https://deno.land/x/drollup@2.37.1+0.5.1/example/src/mod.ts",
  output: {
    dir: "./dist",
    format: "es",
    sourcemap: true
  },
};
const bundle = await rollup(options);
await bundle.write(options.output);
```
which can then be run with `deno run`. If you change `example/rollup.build.ts` to use the full URL rather than a local file, you can then run it with `deno run -A --unstable https://deno.land/x/drollup@2.37.1+0.5.1/example/rollup.build.ts`.

I think this is better for people wanting to try it out. In fact, people can fork the repo and edit their fork to try different things. No need to install anything.

**Comment by cmorten** [comment]
Hey @probins 👋 

Good shout! We can update the various READMEs to point out that the example can be run without installing or cloning anything ☺️It certainly is one of the cool features of Deno!

**Comment by probins** [comment]
wow, that was a fast response 😄 

Wandering off-topic ... if you're updating the main Readme, you should fix the Contributing link too.

**Comment by cmorten** [comment]
> wow, that was a fast response 😄
> 
> Wandering off-topic ... if you're updating the main Readme, you should fix the Contributing link too.

Ah oops 😅 yep good spot!

**Comment by cmorten** [comment]
If you spot anything else, feel free to raise another issue / a PR to fix 🚀
