### ISSUE TITLE
Source map file empty

### ISSUE THREAD

**Issue by probins** [cmorten/deno-rollup#8]
# Issue

Setup:

- Deno version: 1.7.0
- v8 version: 8.9.255.3
- Typescript version: 4.1.3
- deno-rollup version: 2.38.0+0.6.1

Content of source map file (for 328k js file) =
`{"version":3,"file":"ol2.js","sources":[],"sourcesContent":[],"names":[],"mappings":";"}`

## Details

Just ran the same config through Denopack and through deno-rollup, using Denopack's terserTransform plugin, as in the deno-rollup example. The output file is the same size in both cases, but Denopack's source map is 1.6MB, whereas deno-rollup's has  no content, as above.

Source map only makes sense with minified code, right?

**Comment by cmorten** [comment]
Source maps are valid for any transpiled code, not just minified, as they provide a mapping from the transformed version back to the original.

Can you share the Rollup config options that you used / a simple reproduceable example? I would expect that if you provided flags for source maps then deno-rollup should not be giving you an empty map as you have shared and this is a big.

**Comment by probins** [comment]
hm, I just tried a really simple example, and it output a correct source map. So I shall have to investigate further to try and find out what the difference is (apart from size).

Denopack's output seems to be correct.

**Comment by cmorten** [comment]
Hey @probins this auto-closed when I merged #9, so apologies if premature.

Please could you see if `2.38.0+0.7.0` fixes your issue, and if not, reopen the issue.

**Comment by probins** [comment]
👍 that seems to have fixed the problem, thanks. Makes sense, too, as that build is all built from external files.
